export const CREAR_ANUNCIO = "CREAR_ANUNCIO"

export const LOG_IN = "LOG_IN"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_ERROR = "LOG_IN_ERROR"
export const LOG_OUT_SUCCESS = "LOG_OUT"

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_ERROR = "SIGN_UP_ERROR"

export const FAVORITE_SUCCESS = "FAVORITE_SUCCESS"
export const UNFAVORITE_SUCCESS = "UNFAVORITE_SUCCESS"

